# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signature',
            options={'ordering': ('-created_at',)},
        ),
    ]
