# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_auto_20160709_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
