# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-04 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_auto_20160709_0451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bytessignature',
            old_name='bytes4_signature',
            new_name='unicode_bytes4_signature',
        ),
    ]
