# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-04 19:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_auto_20160804_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='bytessignature',
            name='bytes4_signature',
            field=models.BinaryField(max_length=4, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
