# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-04 19:24
from __future__ import unicode_literals

from django.db import migrations
from sha3 import sha3_256


def force_bytes(value):
    if isinstance(value, bytes):
        return value
    elif isinstance(value, memoryview):
        return bytes(value)
    elif isinstance(value, str):
        return bytes(value, 'utf8')
    else:
        raise TypeError("Unsupported type: {0}".format(type(value)))


def make_4byte_signature(text_signature):
    return sha3_256(force_bytes(text_signature)).digest()[:4]


def populate_bytes4_signature(apps, schema_editor):
    Signature = apps.get_model('registry', 'Signature')
    BytesSignature = apps.get_model('registry', 'BytesSignature')

    for signature in Signature.objects.all():
        signature.bytes_signature, _ = BytesSignature.objects.get_or_create(
            bytes4_signature=make_4byte_signature(signature.text_signature),
        )
        signature.save()

    bytes_signatures_to_remove = BytesSignature.objects.filter(
        signature__isnull=True,
    )
    if bytes_signatures_to_remove.exists():
        print("Removing {0} abandoned bytes signatures".format(
            bytes_signatures_to_remove.count()
        ))
        bytes_signatures_to_remove.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_auto_20160804_1929'),
    ]

    operations = [
        migrations.RunPython(populate_bytes4_signature),
    ]
