# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-04 20:28
from __future__ import unicode_literals

from django.db import migrations


def populate_hex_signature(apps, schema_editor):
    BytesSignature = apps.get_model('registry', 'BytesSignature')

    for bytes_signature in BytesSignature.objects.all():
        bytes_signature.save()


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0009_bytessignature_hex_signature'),
    ]

    operations = [
        migrations.RunPython(populate_hex_signature),
    ]
