# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-04 20:47
from __future__ import unicode_literals

from django.db import migrations


def clean_bad_bytes_signatures(apps, schema_editor):
    BytesSignature = apps.get_model('registry', 'BytesSignature')

    BytesSignature.objects.filter(signature__isnull=True).delete()

    assert not BytesSignature.objects.filter(bytes4_signature=b'').exists()
    assert not BytesSignature.objects.filter(hex_signature='').exists()


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0010_auto_20160804_2028'),
    ]

    operations = [
        migrations.RunPython(clean_bad_bytes_signatures),
    ]
