# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-05 04:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0012_auto_20160805_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bytessignature',
            name='hex_signature',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
