# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-08-03 09:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0014_auto_20200803_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsignature',
            name='bytes_signature',
            field=models.BinaryField(max_length=32, validators=[django.core.validators.MinLengthValidator(32)]),
        ),
        migrations.AlterField(
            model_name='eventsignature',
            name='hex_signature',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(64)]),
        ),
    ]
