# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-08-06 17:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0014_auto_20200806_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bytessignature',
            name='bytes4_signature',
            field=models.BinaryField(max_length=4, unique=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='eventsignature',
            name='text_signature',
            field=models.TextField(unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(4096)]),
        ),
    ]
