# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-08-06 17:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0015_auto_20200806_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsignature',
            name='text_signature',
            field=models.TextField(max_length=4096, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(4096)]),
        ),
    ]
