# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-08-06 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0015_auto_20200803_0923'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventSignature',
        ),
    ]
